"""
Bangalore Parking Lots — Static metadata with GPS coordinates.
File: backend_django/api/bangalore_lots.py

All 30 lots from smart_parking_bengaluru_200k.csv with real Bengaluru lat/lng.
"""

BANGALORE_LOTS = [
    {
        "lot_id": "LOT_01", "lot_name": "MG Road Central Park",
        "lot_type": "Mall", "location_area": "MG Road",
        "total_spaces": 300, "avg_occupancy_pct": 53.8,
        "lat": 12.9753, "lng": 77.6012,
        "price_per_hour": 40,
    },
    {
        "lot_id": "LOT_02", "lot_name": "Jayanagar Shopping Mall",
        "lot_type": "Mall", "location_area": "Jayanagar",
        "total_spaces": 250, "avg_occupancy_pct": 54.1,
        "lat": 12.9254, "lng": 77.5828,
        "price_per_hour": 35,
    },
    {
        "lot_id": "LOT_03", "lot_name": "Bannerghatta Grand Mall",
        "lot_type": "Mall", "location_area": "Bannerghatta",
        "total_spaces": 400, "avg_occupancy_pct": 53.8,
        "lat": 12.8975, "lng": 77.5979,
        "price_per_hour": 45,
    },
    {
        "lot_id": "LOT_04", "lot_name": "Orion Mall Rajajinagar",
        "lot_type": "Mall", "location_area": "Rajajinagar",
        "total_spaces": 500, "avg_occupancy_pct": 54.1,
        "lat": 12.9906, "lng": 77.5524,
        "price_per_hour": 50,
    },
    {
        "lot_id": "LOT_05", "lot_name": "Phoenix Marketcity",
        "lot_type": "Mall", "location_area": "Whitefield",
        "total_spaces": 600, "avg_occupancy_pct": 53.8,
        "lat": 12.9716, "lng": 77.7493,
        "price_per_hour": 50,
    },
    {
        "lot_id": "LOT_06", "lot_name": "Mantri Square Mall",
        "lot_type": "Mall", "location_area": "Malleswaram",
        "total_spaces": 450, "avg_occupancy_pct": 54.0,
        "lat": 12.9997, "lng": 77.5705,
        "price_per_hour": 45,
    },
    {
        "lot_id": "LOT_07", "lot_name": "Forum Koramangala",
        "lot_type": "Mall", "location_area": "Koramangala",
        "total_spaces": 350, "avg_occupancy_pct": 53.9,
        "lat": 12.9343, "lng": 77.6101,
        "price_per_hour": 45,
    },
    {
        "lot_id": "LOT_08", "lot_name": "Whitefield IT Hub",
        "lot_type": "Office", "location_area": "Whitefield",
        "total_spaces": 500, "avg_occupancy_pct": 42.3,
        "lat": 12.9698, "lng": 77.7500,
        "price_per_hour": 30,
    },
    {
        "lot_id": "LOT_09", "lot_name": "Koramangala Square",
        "lot_type": "Office", "location_area": "Koramangala",
        "total_spaces": 200, "avg_occupancy_pct": 42.3,
        "lat": 12.9352, "lng": 77.6245,
        "price_per_hour": 30,
    },
    {
        "lot_id": "LOT_10", "lot_name": "HSR Layout Hub",
        "lot_type": "Office", "location_area": "HSR Layout",
        "total_spaces": 180, "avg_occupancy_pct": 42.3,
        "lat": 12.9116, "lng": 77.6474,
        "price_per_hour": 25,
    },
    {
        "lot_id": "LOT_11", "lot_name": "Electronic City Park",
        "lot_type": "Office", "location_area": "Electronic City",
        "total_spaces": 600, "avg_occupancy_pct": 42.2,
        "lat": 12.8456, "lng": 77.6603,
        "price_per_hour": 25,
    },
    {
        "lot_id": "LOT_12", "lot_name": "Manyata Tech Park",
        "lot_type": "Office", "location_area": "Hebbal",
        "total_spaces": 800, "avg_occupancy_pct": 42.1,
        "lat": 13.0474, "lng": 77.6190,
        "price_per_hour": 30,
    },
    {
        "lot_id": "LOT_13", "lot_name": "Bagmane Tech Park",
        "lot_type": "Office", "location_area": "CV Raman Nagar",
        "total_spaces": 700, "avg_occupancy_pct": 42.4,
        "lat": 12.9760, "lng": 77.6546,
        "price_per_hour": 30,
    },
    {
        "lot_id": "LOT_14", "lot_name": "RMZ Ecospace",
        "lot_type": "Office", "location_area": "Bellandur",
        "total_spaces": 550, "avg_occupancy_pct": 42.2,
        "lat": 12.9270, "lng": 77.6870,
        "price_per_hour": 35,
    },
    {
        "lot_id": "LOT_15", "lot_name": "Yelahanka Township Office",
        "lot_type": "Office", "location_area": "Yelahanka",
        "total_spaces": 220, "avg_occupancy_pct": 42.2,
        "lat": 13.1004, "lng": 77.5963,
        "price_per_hour": 20,
    },
    {
        "lot_id": "LOT_16", "lot_name": "Manipal Hospital Parking",
        "lot_type": "Hospital", "location_area": "Old Airport Road",
        "total_spaces": 200, "avg_occupancy_pct": 59.6,
        "lat": 12.9591, "lng": 77.6477,
        "price_per_hour": 20,
    },
    {
        "lot_id": "LOT_17", "lot_name": "Fortis Cunningham Road",
        "lot_type": "Hospital", "location_area": "Cunningham Road",
        "total_spaces": 150, "avg_occupancy_pct": 59.6,
        "lat": 12.9935, "lng": 77.5956,
        "price_per_hour": 20,
    },
    {
        "lot_id": "LOT_18", "lot_name": "Narayana Health City",
        "lot_type": "Hospital", "location_area": "Bommasandra",
        "total_spaces": 300, "avg_occupancy_pct": 59.8,
        "lat": 12.8345, "lng": 77.6739,
        "price_per_hour": 15,
    },
    {
        "lot_id": "LOT_19", "lot_name": "Indiranagar Metro Park",
        "lot_type": "Street", "location_area": "Indiranagar",
        "total_spaces": 120, "avg_occupancy_pct": 50.3,
        "lat": 12.9784, "lng": 77.6408,
        "price_per_hour": 15,
    },
    {
        "lot_id": "LOT_20", "lot_name": "Hebbal Flyover Park",
        "lot_type": "Street", "location_area": "Hebbal",
        "total_spaces": 100, "avg_occupancy_pct": 50.2,
        "lat": 13.0358, "lng": 77.5970,
        "price_per_hour": 10,
    },
    {
        "lot_id": "LOT_21", "lot_name": "Marathahalli Bridge Park",
        "lot_type": "Street", "location_area": "Marathahalli",
        "total_spaces": 150, "avg_occupancy_pct": 50.2,
        "lat": 12.9561, "lng": 77.7010,
        "price_per_hour": 10,
    },
    {
        "lot_id": "LOT_22", "lot_name": "Yeshwanthpur Circle Park",
        "lot_type": "Street", "location_area": "Yeshwanthpur",
        "total_spaces": 130, "avg_occupancy_pct": 50.2,
        "lat": 13.0229, "lng": 77.5466,
        "price_per_hour": 10,
    },
    {
        "lot_id": "LOT_23", "lot_name": "Basavanagudi Street Park",
        "lot_type": "Street", "location_area": "Basavanagudi",
        "total_spaces": 90, "avg_occupancy_pct": 50.3,
        "lat": 12.9416, "lng": 77.5757,
        "price_per_hour": 10,
    },
    {
        "lot_id": "LOT_24", "lot_name": "Shivajinagar Bus Stand",
        "lot_type": "Street", "location_area": "Shivajinagar",
        "total_spaces": 110, "avg_occupancy_pct": 50.3,
        "lat": 12.9858, "lng": 77.6012,
        "price_per_hour": 10,
    },
    {
        "lot_id": "LOT_25", "lot_name": "Kempegowda Airport P1",
        "lot_type": "Airport", "location_area": "Devanahalli",
        "total_spaces": 1000, "avg_occupancy_pct": 64.4,
        "lat": 13.1979, "lng": 77.7063,
        "price_per_hour": 60,
    },
    {
        "lot_id": "LOT_26", "lot_name": "Kempegowda Airport P2",
        "lot_type": "Airport", "location_area": "Devanahalli",
        "total_spaces": 800, "avg_occupancy_pct": 64.1,
        "lat": 13.2002, "lng": 77.7089,
        "price_per_hour": 60,
    },
    {
        "lot_id": "LOT_27", "lot_name": "Majestic Bus Terminal",
        "lot_type": "Transit", "location_area": "Majestic",
        "total_spaces": 200, "avg_occupancy_pct": 56.1,
        "lat": 12.9775, "lng": 77.5713,
        "price_per_hour": 20,
    },
    {
        "lot_id": "LOT_28", "lot_name": "KSR Railway Station Park",
        "lot_type": "Transit", "location_area": "Majestic",
        "total_spaces": 250, "avg_occupancy_pct": 56.3,
        "lat": 12.9762, "lng": 77.5699,
        "price_per_hour": 20,
    },
    {
        "lot_id": "LOT_29", "lot_name": "Sarjapur Road Apts",
        "lot_type": "Residential", "location_area": "Sarjapur Road",
        "total_spaces": 160, "avg_occupancy_pct": 47.8,
        "lat": 12.9082, "lng": 77.6938,
        "price_per_hour": 15,
    },
    {
        "lot_id": "LOT_30", "lot_name": "JP Nagar Society Park",
        "lot_type": "Residential", "location_area": "JP Nagar",
        "total_spaces": 140, "avg_occupancy_pct": 47.9,
        "lat": 12.9080, "lng": 77.5835,
        "price_per_hour": 15,
    },
]
